### ISSUE TITLE
Total votes count

### ISSUE THREAD

**Issue by Doksperiments** [SamueleLorefice/ArmABot#8]
A line at the end of the dynamic poll, containing how many people voted, how many are left or how many there are in total

**Comment by SamueleLorefice** [comment]
Technically we already have a count of the number of votes per choice. Adding the total count is really easy. Getting how many are left, not exactly. Will look into it.

**Comment by SamueleLorefice** [comment]
we will mark only the required members needed for the operation due to telegram not having a method to get the user informations of the members into the group but only the member count. To have a whole member + information count would require tracking all the messages into the group. TBH too much work for almost nothing.
